### ISSUE TITLE
50강 테스트데이터 입력 시 오류

### ISSUE THREAD

**Issue by dabok407** [ahastudio/fastcampus-eatgo#13]
```
java.lang.NullPointerException
	at com.example.study.sampledata.CategorySample.createSample(CategorySample.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

이와 같은 오류가 발생합니다. 이전 강의 재반복하여 다시 학습 하였는데 동일한 오류가 

지속적으로 발생됩니다.

**Comment by ahastudio** [comment]
`CategorySample`은 어떤 건가요? 제 강의가 맞나요?
