### ISSUE TITLE
16강 JPA수업 다 적용하고 Test All 하게되면 create 에서 에러가 납니다

### ISSUE THREAD

**Issue by betogirls** [ahastudio/fastcampus-eatgo#56]
답변이 언제 달릴지는 모르겠지만 일단 문의 드립니다.

예전에도 이와 비슷한 질문이 달렸던데 문의가 해결이 되어서 완료처리를 하신건지 어쩐건지는 모르지만
저만 이상한건지 분명히 수업대로 따라했음에도 불구하고 에러가 나는데 다른분들은 에러가 나도 그냥 진행을 하시는건지
혹시몰라서 수업하던 소스를 전부 삭제하고 1강부터 다시 따라했는데도 에러가나는거 보면 제가 잘못한건 아닌거 같은데
머가문제인지 모르겠네요

16강 전까지도 전부 따라하면서 Test All 돌렸을때 문제가 없는거 확인을 했구요 16강 수업들어와서 아샬님이 진행하시는대로 전부 따라하고 최종적으로 Test All 을 돌려보면 `RestaurantControllerTest` 의 `create` 부분에서 에러가 납니다

아래가 에러 내용이구요 레스토랑 아이디를 리턴을 못하는거 같습니다

```
java.lang.AssertionError: Response header 'location' 
Expected :/restaurants/1234
Actual   :/restaurants/null
<Click to see difference>


	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:98)
	at org.springframework.test.web.servlet.result.HeaderResultMatchers.lambda$string$2(HeaderResultMatchers.java:78)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:196)
	at kr.co.fastcampus.Eatgo.interfaces.RestaurantControllerTest.create(RestaurantControllerTest.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

![Error1](https://user-images.githubusercontent.com/68468093/87869670-859f0200-c9dc-11ea-8a48-7682e8664056.png)
![RestaurantService](https://user-images.githubusercontent.com/68468093/87869681-9485b480-c9dc-11ea-821f-757c8271c8a3.png)
![RestaurantServiceTest](https://user-images.githubusercontent.com/68468093/87869687-98193b80-c9dc-11ea-9d96-feb9998f20bb.png)
![Restaurant](https://user-images.githubusercontent.com/68468093/87869689-9a7b9580-c9dc-11ea-97da-0b3bc80658dc.png)
![RestaurantRepository](https://user-images.githubusercontent.com/68468093/87869690-9e0f1c80-c9dc-11ea-8e42-4c8991a69b48.png)
![RestaurantTests](https://user-images.githubusercontent.com/68468093/87869693-a0717680-c9dc-11ea-8222-807a71e4ef4c.png)
![MenuItem](https://user-images.githubusercontent.com/68468093/87869698-a404fd80-c9dc-11ea-9615-37c84cc612e7.png)
![MenuItemRepository](https://user-images.githubusercontent.com/68468093/87869699-a5cec100-c9dc-11ea-83ff-0e505cc956c8.png)
![RestaurantController](https://user-images.githubusercontent.com/68468093/87869701-a8311b00-c9dc-11ea-8d09-317c465ea9ab.png)
![RestaurantControllerTest](https://user-images.githubusercontent.com/68468093/87869703-a9fade80-c9dc-11ea-9f52-8448f643cc7a.png)

**Comment by ahastudio** [comment]
영상 편집 과정에서 해당 부분이 누락된 것 같습니다. [완성된 코드](https://github.com/ahastudio/fastcampus-eatgo/blob/master/eatgo-admin-api/src/test/java/kr/co/fastcampus/eatgo/interfaces/RestaurantControllerTests.java)를 참고하세요.

![Screenshot](https://user-images.githubusercontent.com/36392/94370698-6505cd80-012c-11eb-9940-22f7d98025c4.png)
